import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

import "../../app/global.css"
import 'swiper/css';
import Footer from "./components/layout/Footer";
import cn from "classnames";
import Header from "./components/layout/Header/Header";

const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "relative")}>
            <Header />
            {children}
            <Footer />
      </body>
    </html>
  );
}
