spring:
  application:
    name: shopstuffing
  data:
    mongodb:
      uri: mongodb://localhost:27017/ShopStuffingDB

jwt:
  signerKey: "PTHWMfnVCJFIXp1pRSPPRh4UbFcAIXBEp7GhaNzi/f0Fa+0rzMjVdNnpP7Pt8Zzv"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

open:
  api:
    title: API Document
    version: v1.0.0
    description: Test API Service
    serverUrl: http://localhost:8080
    serverName: server develop